# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: 931453811831.dkr.ecr.us-east-2.amazonaws.com/plate-search
        auth:
         username: $username
         password: $password
        aws_auth:
          aws_access_key_id:  $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
  deploy:
      docker:
        - image: 931453811831.dkr.ecr.us-east-2.amazonaws.com/plate-search:latest
          aws_auth:
            aws_access_key_id: $AWS_ACCESS_KEY_ID
            aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
      steps:
        - run:
            name: "Full Test Suite"
            command: "testing...."
        - run:
            name: "Deploy to Production Infrastructure"
            command: "something something darkside.... cli"
workflows:
  version: 2
  main:
    jobs:
      - build:
          context: variables
          filters:
            tags:
              only: /^\d{4}\.\d+$/
      - deploy:
          requires:
            - build
          context: variables
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d{4}\.\d+$/

